/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package edu.ijse.mvc.swing.view;

import edu.ijse.mvc.swing.controller.InvoiceController;
import edu.ijse.mvc.swing.dto.InvoiceDto;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.util.ArrayList;

/**
 *
 * @author lenovo
 */
public class ManageInvoice extends javax.swing.JPanel {

    private final InvoiceController invoiceController = new InvoiceController();
    /**
     * Creates new form ManageCustomer
     */
    public ManageInvoice() {
        initComponents();
        loadTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        titleLabel = new javax.swing.JLabel();
        invoiceIDLabel = new javax.swing.JLabel();
        invoiceIDTxt = new javax.swing.JTextField();
        CustomerIDTxt = new javax.swing.JTextField();
        customerIDLabel = new javax.swing.JLabel();
        meterIDLabel = new javax.swing.JLabel();
        unitsTxt = new javax.swing.JTextField();
        periodStartLabel = new javax.swing.JLabel();
        saveBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        detailsTabel = new javax.swing.JTable();
        updateBtn = new javax.swing.JButton();
        deleteBtn = new javax.swing.JButton();
        resetBtn = new javax.swing.JButton();
        periodEndLabel = new javax.swing.JLabel();
        startDatePicker = new de.wannawork.jcalendar.JCalendarComboBox();
        endDatePicker = new de.wannawork.jcalendar.JCalendarComboBox();
        unitsLabel = new javax.swing.JLabel();
        materIDTxt = new javax.swing.JTextField();
        statusLabel = new javax.swing.JLabel();
        statusPicker = new javax.swing.JComboBox<>();
        amountTxt = new javax.swing.JLabel();
        totalAmountLabel = new javax.swing.JLabel();
        calculateBtn = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(1052, 768));

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(1052, 768));

        titleLabel.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        titleLabel.setText("Invoice Management System");

        invoiceIDLabel.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        invoiceIDLabel.setText("Invoice ID :");

        invoiceIDTxt.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N

        CustomerIDTxt.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N

        customerIDLabel.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        customerIDLabel.setText("Customer ID :");

        meterIDLabel.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        meterIDLabel.setText("Meter ID :");

        unitsTxt.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N

        periodStartLabel.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        periodStartLabel.setText("Period Start : ");

        saveBtn.setBackground(new java.awt.Color(0, 102, 204));
        saveBtn.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        saveBtn.setForeground(new java.awt.Color(255, 255, 255));
        saveBtn.setText("Save");
        saveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBtnActionPerformed(evt);
            }
        });

        detailsTabel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "invoice_id", "customer_id", "meter_id", "consumption_units", "period_start", "period_end", "status", "total_amount"
            }
        ));
        detailsTabel.setRowHeight(25);
        jScrollPane1.setViewportView(detailsTabel);

        updateBtn.setBackground(new java.awt.Color(0, 102, 204));
        updateBtn.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        updateBtn.setForeground(new java.awt.Color(255, 255, 255));
        updateBtn.setText("Update");
        updateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBtnActionPerformed(evt);
            }
        });

        deleteBtn.setBackground(new java.awt.Color(255, 0, 0));
        deleteBtn.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        deleteBtn.setForeground(new java.awt.Color(255, 255, 255));
        deleteBtn.setText("Delete");
        deleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBtnActionPerformed(evt);
            }
        });

        resetBtn.setBackground(new java.awt.Color(204, 204, 255));
        resetBtn.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        resetBtn.setForeground(new java.awt.Color(255, 255, 255));
        resetBtn.setText("Reset");
        resetBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetBtnActionPerformed(evt);
            }
        });

        periodEndLabel.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        periodEndLabel.setText("Period End : ");

        unitsLabel.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        unitsLabel.setText("Consumption Units :");

        materIDTxt.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N

        statusLabel.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        statusLabel.setText("Status");

        statusPicker.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Draft ", "Pending / Open", "Sent / Issued", "Partially Paid", "Paid", "Overdue / Past Due", "Cancelled / Voided", "Rejected / Disputed", "Refunded / Credited", "Written Off" }));

        amountTxt.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N

        totalAmountLabel.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        totalAmountLabel.setText("Total Amount :");

        calculateBtn.setBackground(new java.awt.Color(102, 255, 0));
        calculateBtn.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        calculateBtn.setForeground(new java.awt.Color(51, 51, 51));
        calculateBtn.setText("Calculate");
        calculateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculateBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(titleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 367, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 987, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(meterIDLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(1, 1, 1)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(invoiceIDTxt)
                                    .addComponent(startDatePicker, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(materIDTxt)
                                    .addComponent(statusPicker, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(totalAmountLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(322, 322, 322))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(calculateBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(27, 27, 27)
                                    .addComponent(saveBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(28, 28, 28)
                                    .addComponent(updateBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(28, 28, 28)
                                    .addComponent(deleteBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(28, 28, 28)
                                    .addComponent(resetBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(invoiceIDLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(periodStartLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE)
                                        .addComponent(statusLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGap(335, 335, 335)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(customerIDLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(periodEndLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGap(18, 18, 18)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(CustomerIDTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(endDatePicker, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(unitsLabel)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(unitsTxt)
                                                .addComponent(amountTxt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))))))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(titleLabel)
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(invoiceIDLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(CustomerIDTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(customerIDLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(17, 17, 17)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(unitsTxt)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(meterIDLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(unitsLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(endDatePicker, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(startDatePicker, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(periodStartLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(periodEndLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(statusLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(statusPicker, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(amountTxt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(totalAmountLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(43, 43, 43))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(invoiceIDTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(17, 17, 17)
                        .addComponent(materIDTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(saveBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(updateBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deleteBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(resetBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(calculateBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void saveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBtnActionPerformed
        saveInvoice();
    }//GEN-LAST:event_saveBtnActionPerformed

    private void updateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBtnActionPerformed
       updateInvoice();
    }//GEN-LAST:event_updateBtnActionPerformed

    private void deleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtnActionPerformed
        deleteInvoice();
    }//GEN-LAST:event_deleteBtnActionPerformed

    private void resetBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetBtnActionPerformed
       reset();
    }//GEN-LAST:event_resetBtnActionPerformed
    
    private void calculateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calculateBtnActionPerformed
       calculateTotalAmount();
    }//GEN-LAST:event_calculateBtnActionPerformed

    public void calculateTotalAmount() {
        try {
            int units = Integer.parseInt(unitsTxt.getText().trim());
            double bill = 0;

            if (units <= 60) {
                if (units <= 30) {
                    bill = (units * 8) + 150;
                } else {
                    bill = (30 * 8) + ((units - 30) * 20) + 150;
                }
            } else {
                bill = 400;
                if (units <= 60) {
                    bill += units * 30;
                } else if (units <= 90) {
                    bill += (60 * 30) + ((units - 60) * 37);
                } else if (units <= 120) {
                    bill += (60 * 30) + (30 * 37) + ((units - 90) * 42);
                } else if (units <= 180) {
                    bill += (60 * 30) + (30 * 37) + (30 * 42) + ((units - 120) * 50);
                } else {
                    bill += (60 * 30) + (30 * 37) + (30 * 42) + (60 * 50) + ((units - 180) * 75);
                }
            }

            amountTxt.setText(String.valueOf(bill));
        } catch (NumberFormatException e) {
            amountTxt.setText("0");
        }
    }

    public void reset() {
        invoiceIDTxt.setText("");
        CustomerIDTxt.setText("");
        materIDTxt.setText("");
        startDatePicker.setDate(null);
        endDatePicker.setDate(null);
        unitsTxt.setText("");
        amountTxt.setText("");
        statusPicker.setSelectedIndex(-1);

    }

    public void saveInvoice() {

        java.util.Date utilDate = startDatePicker.getDate();
        java.sql.Date sqlDate = new java.sql.Date(utilDate.getTime());

        java.util.Date utilDate2 = endDatePicker.getDate();
        java.sql.Date sqlDate2 = new java.sql.Date(utilDate2.getTime());

        try {
            InvoiceDto invoiceDto = new InvoiceDto(
                    invoiceIDTxt.getText(),
                    CustomerIDTxt.getText(),
                    materIDTxt.getText(),
                    sqlDate,
                    sqlDate2,
                    Integer.parseInt(unitsTxt.getText()),
                    Double.parseDouble(amountTxt.getText()),
                    (String) statusPicker.getSelectedItem()
            );
            String rsp = invoiceController.addInvoice(invoiceDto);
            JOptionPane.showMessageDialog(this,rsp);
            reset();
            loadTable();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,e.getMessage());
        }
    }

    public void updateInvoice() {

        java.util.Date utilDate = startDatePicker.getDate();
        java.sql.Date sqlDate = new java.sql.Date(utilDate.getTime());

        java.util.Date utilDate2 = endDatePicker.getDate();
        java.sql.Date sqlDate2 = new java.sql.Date(utilDate2.getTime());

        try {
            InvoiceDto invoiceDto = new InvoiceDto(
                    invoiceIDTxt.getText(),
                    CustomerIDTxt.getText(),
                    materIDTxt.getText(),
                    sqlDate,
                    sqlDate2,
                    Integer.parseInt(unitsTxt.getText()),
                    Double.parseDouble(amountTxt.getText()),
                    (String) statusPicker.getSelectedItem()
            );
            String rsp = invoiceController.updateInvoice(invoiceDto);
            JOptionPane.showMessageDialog(this,rsp);
            reset();
            loadTable();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,e.getMessage());
        }
    }

    public void deleteInvoice() {
        try {
            String rsp = invoiceController.deleteInvoice(invoiceIDTxt.getText());
            JOptionPane.showMessageDialog(this,rsp);
            reset();
            loadTable();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,e.getMessage());
        }
    }

    public void loadTable(){

        DefaultTableModel dtm = (DefaultTableModel) detailsTabel.getModel();
        dtm.setRowCount(0);

        try {
            for (InvoiceDto invoiceDto : invoiceController.getAllInvoice()){
                ArrayList <Object> row = new ArrayList<>();
                row.add(invoiceDto.getId());
                row.add(invoiceDto.getCustomerID());
                row.add(invoiceDto.getMeterID());
                row.add(invoiceDto.getConsumptionUnits());
                row.add(invoiceDto.getPeriodStart());
                row.add(invoiceDto.getPeriodEnd());
                row.add(invoiceDto.getTotal_amount());
                row.add(invoiceDto.getStatus());
                dtm.addRow(row.toArray());
            }

        } catch (Exception e) {
                JOptionPane.showMessageDialog(this,e.getMessage());
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CustomerIDTxt;
    private javax.swing.JLabel amountTxt;
    private javax.swing.JButton calculateBtn;
    private javax.swing.JLabel customerIDLabel;
    private javax.swing.JButton deleteBtn;
    private javax.swing.JTable detailsTabel;
    private de.wannawork.jcalendar.JCalendarComboBox endDatePicker;
    private javax.swing.JLabel invoiceIDLabel;
    private javax.swing.JTextField invoiceIDTxt;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField materIDTxt;
    private javax.swing.JLabel meterIDLabel;
    private javax.swing.JLabel periodEndLabel;
    private javax.swing.JLabel periodStartLabel;
    private javax.swing.JButton resetBtn;
    private javax.swing.JButton saveBtn;
    private de.wannawork.jcalendar.JCalendarComboBox startDatePicker;
    private javax.swing.JLabel statusLabel;
    private javax.swing.JComboBox<String> statusPicker;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JLabel totalAmountLabel;
    private javax.swing.JLabel unitsLabel;
    private javax.swing.JTextField unitsTxt;
    private javax.swing.JButton updateBtn;
    // End of variables declaration//GEN-END:variables
}
