/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package edu.ijse.mvc.swing.view;

import javax.swing.*;
import java.awt.*;

/**
 *
 * @author lenovo
 */
public class ManageMainMenu extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ManageMainMenu.class.getName());

    /**
     * Creates new form ManageMainMenu
     */
    public ManageMainMenu() {
        initComponents();
        setTitle("Electricity Management System");
        setDefaultCloseOperation(EXIT_ON_CLOSE);
        setResizable(false);
        setMinimumSize(new Dimension(1366,768));
        leftPanel.setLayout(new BorderLayout());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menuPanel = new javax.swing.JPanel();
        titleLabel = new javax.swing.JLabel();
        customerBtn = new javax.swing.JButton();
        meterBtn = new javax.swing.JButton();
        meterReadingBtn = new javax.swing.JButton();
        tariffBtn = new javax.swing.JButton();
        tariffSlabBtn = new javax.swing.JButton();
        invoiceBtn = new javax.swing.JButton();
        paymentBtn = new javax.swing.JButton();
        logOutBtn = new javax.swing.JButton();
        employeeBtn = new javax.swing.JButton();
        leftPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        menuPanel.setBackground(new java.awt.Color(204, 204, 255));

        titleLabel.setFont(new java.awt.Font("Liberation Sans", 1, 22)); // NOI18N
        titleLabel.setText("Main Menu");

        customerBtn.setBackground(new java.awt.Color(51, 255, 51));
        customerBtn.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        customerBtn.setText("Manage Customer");
        customerBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customerBtnActionPerformed(evt);
            }
        });

        meterBtn.setBackground(new java.awt.Color(51, 255, 0));
        meterBtn.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        meterBtn.setText("Manage Meter");
        meterBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                meterBtnActionPerformed(evt);
            }
        });

        meterReadingBtn.setBackground(new java.awt.Color(51, 255, 0));
        meterReadingBtn.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        meterReadingBtn.setText("Manage Meter Reading");
        meterReadingBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                meterReadingBtnActionPerformed(evt);
            }
        });

        tariffBtn.setBackground(new java.awt.Color(51, 255, 0));
        tariffBtn.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        tariffBtn.setText("Manage Tariff");
        tariffBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tariffBtnActionPerformed(evt);
            }
        });

        tariffSlabBtn.setBackground(new java.awt.Color(51, 255, 0));
        tariffSlabBtn.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        tariffSlabBtn.setText("Manage Tariff Slab");
        tariffSlabBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tariffSlabBtnActionPerformed(evt);
            }
        });

        invoiceBtn.setBackground(new java.awt.Color(51, 255, 0));
        invoiceBtn.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        invoiceBtn.setText("Manage Invoice");
        invoiceBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                invoiceBtnActionPerformed(evt);
            }
        });

        paymentBtn.setBackground(new java.awt.Color(51, 255, 0));
        paymentBtn.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        paymentBtn.setText("Manage Payment");
        paymentBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paymentBtnActionPerformed(evt);
            }
        });

        logOutBtn.setBackground(new java.awt.Color(255, 0, 51));
        logOutBtn.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        logOutBtn.setText("Log Out");
        logOutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logOutBtnActionPerformed(evt);
            }
        });

        employeeBtn.setBackground(new java.awt.Color(51, 255, 0));
        employeeBtn.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        employeeBtn.setText("Manage Employee");
        employeeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                employeeBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout menuPanelLayout = new javax.swing.GroupLayout(menuPanel);
        menuPanel.setLayout(menuPanelLayout);
        menuPanelLayout.setHorizontalGroup(
            menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuPanelLayout.createSequentialGroup()
                .addGroup(menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(menuPanelLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(paymentBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(invoiceBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tariffSlabBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tariffBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(meterReadingBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 238, Short.MAX_VALUE)
                            .addComponent(meterBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(customerBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(logOutBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(employeeBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(menuPanelLayout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addComponent(titleLabel)))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        menuPanelLayout.setVerticalGroup(
            menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuPanelLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(titleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(customerBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(meterBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(employeeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(meterReadingBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(tariffBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(tariffSlabBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(invoiceBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(paymentBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(logOutBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(136, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout leftPanelLayout = new javax.swing.GroupLayout(leftPanel);
        leftPanel.setLayout(leftPanelLayout);
        leftPanelLayout.setHorizontalGroup(
            leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        leftPanelLayout.setVerticalGroup(
            leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(menuPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(leftPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(leftPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(menuPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void customerBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customerBtnActionPerformed
        loadUI("customer");
    }//GEN-LAST:event_customerBtnActionPerformed

    private void meterBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_meterBtnActionPerformed
        loadUI("meter");
    }//GEN-LAST:event_meterBtnActionPerformed

    private void meterReadingBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_meterReadingBtnActionPerformed
        loadUI("meterReading");
    }//GEN-LAST:event_meterReadingBtnActionPerformed

    private void tariffBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tariffBtnActionPerformed
        loadUI("tariff");
    }//GEN-LAST:event_tariffBtnActionPerformed

    private void tariffSlabBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tariffSlabBtnActionPerformed
        loadUI("tariffSlab");
    }//GEN-LAST:event_tariffSlabBtnActionPerformed

    private void invoiceBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_invoiceBtnActionPerformed
        loadUI("invoice");
    }//GEN-LAST:event_invoiceBtnActionPerformed

    private void paymentBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paymentBtnActionPerformed
        loadUI("payment");
    }//GEN-LAST:event_paymentBtnActionPerformed

    private void logOutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logOutBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_logOutBtnActionPerformed

    private void employeeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_employeeBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_employeeBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ManageMainMenu().setVisible(true));
    }

    public void loadUI(String panelName){
        JPanel panelToLoad = null;

        switch (panelName){
            case "customer":
                panelToLoad = new ManageCustomer();
                break;
            case "meter" :
                panelToLoad = new ManageMeter();
                break;
            case "meterReading" :
                panelToLoad = new ManageMeterReading();
                break;
            case "tariff" :
                panelToLoad = new ManageTariff();
                break;
            case "tariffSlab" :
                panelToLoad = new ManageTariffSlab();
                break;
            case "invoice" :
                panelToLoad = new ManageInvoice();
                break;
            case "payment" :
                panelToLoad = new ManagePayment();
                break;
        }

        if(panelToLoad != null){
            leftPanel.removeAll();
            leftPanel.add(panelToLoad, BorderLayout.CENTER);
            leftPanel.revalidate();
            leftPanel.repaint();
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton customerBtn;
    private javax.swing.JButton employeeBtn;
    private javax.swing.JButton invoiceBtn;
    private javax.swing.JPanel leftPanel;
    private javax.swing.JButton logOutBtn;
    private javax.swing.JPanel menuPanel;
    private javax.swing.JButton meterBtn;
    private javax.swing.JButton meterReadingBtn;
    private javax.swing.JButton paymentBtn;
    private javax.swing.JButton tariffBtn;
    private javax.swing.JButton tariffSlabBtn;
    private javax.swing.JLabel titleLabel;
    // End of variables declaration//GEN-END:variables
}
